---
- name: Playbook for upgrading the RPis
  hosts: picluster
  gather_facts: no
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        force_apt_get: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
