#!/usr/bin/zsh

#----------------------------------------------------#
# Give Ansible a password to work with for the hosts #
#----------------------------------------------------#

# Bash
# read -p "What is the cluster password? [raspberry]: " cluster_password
# Currently use Zsh
read "?What is the cluster password? [raspberry]: " cluster_password
cluster_password=${cluster_password:-raspberry} # if nothing read, sets default to raspberry
export CLUSTER_PASSWORD=$cluster_password

echo "Set $CLUSTER_PASSWORD successfully"
