#!/usr/bin/zsh

export HOMELAB_DIR="~/github/homelab/ansible"
export PLAYBOOK_DIR="~/github/homelab/ansible/playbooks"

# Ping
alias ping_cluster="ansible-playbook $PLAYBOOK_DIR/ping.yml -i $HOMELAB_DIR/hosts"

# Reboot
alias restart_cluster="ansible-playbook $PLAYBOOK_DIR/reboot.yml -i $HOMELAB_DIR/hosts"

# Setup cluster [assuming they are rpi at the moment]
alias setup_cluster="ansible-playbook $PLAYBOOK_DIR/setup.yml -i $HOMELAB_DIR/hosts"

# Shutdown
alias poweroff_cluster="ansible-playbook $PLAYBOOK_DIR/shutdown.yml -i $HOMELAB_DIR/hosts"

# Upgrade
alias upgrade_cluster="ansible-playbook $PLAYBOOK_DIR/upgrade.yml -i $HOMELAB_DIR/hosts"

# Signal script success
echo "Cluster commands now available!"
