#!/usr/bin/zsh

homelab_dir=$(find ~/github -name homelab) ||  { echo 'No homelab found :(' ; exit 1; }
playbook_dir=$(find $homelab_dir -name playbooks)

for file in $playbook_dir/*; do
	playbook_name=${$(basename -- $file)%.*}
	echo "Adding ${playbook_name}_cluster command"
	alias "${playbook_name}_cluster"="ansible-playbook $file -i "${homelab_dir}/ansible/hosts""
done

echo "Cluster commands now available!"
